[runtime] Use common protobuf in rumtime.rpc
fixstars/arachne pull request #9
Opened 2022-04-19 05:06 UTC by ry3s

## Changes 
* Unify `{tvm, tflite, onnx}runtime.proto` into `runtime.proto` .
* Update tests.
  * Run all tests including `test_edge.py` .

2022-04-19 05:09 UTC, ry3s commented
There are warnings in `test_edge.py` . Maybe need changes.
```
tests/runtime/rpc/device/test_edge.py::test_tvm_runtime_rpc
  /workspaces/arachne/python/arachne/utils/version_utils.py:13: PendingDeprecationWarning: dist() and linux_distribution() functions are deprecated in Python 3.5
    dist = platform.linux_distribution()[0]

tests/runtime/rpc/device/test_edge.py::test_tvm_runtime_rpc
  /workspaces/arachne/python/arachne/utils/version_utils.py:42: PendingDeprecationWarning: dist() and linux_distribution() functions are deprecated in Python 3.5
    dist = platform.linux_distribution()[0]
```

2022-04-20 05:35 UTC, ry3s commented
Commonize servicer and client into one file 

* `servicer/{tvm, onnx, tflite}.py` -> `servicer.py`
* `client/{tvm, onnx, tflite}.py` -> `client.py`
* Add type assertion of `idx` to `runtime.onnx.py` and `runtime.tflite.py`

2022-04-20 05:37 UTC, tk1012 commented
> Commonize servicer and client into one file
> 
> * `servicer/{tvm, onnx, tflite}.py` -> `servicer.py`
> * `client/{tvm, onnx, tflite}.py` -> `client.py`
> * Add type assertion of `idx` to `runtime.onnx.py` and `runtime.tflite.py`

- [ ] modify `arachne.runtime.rpc.init` like `arachne.runtime.init` (i.e., add the `runtime:str` argument)

2022-04-21 03:42 UTC, tk1012 commented on python/arachne/runtime/rpc/__init__.py
> +    return RuntimeClient(channel, runtime, **args, **kwargs)
Could you assign `package_tar` and `model_file` directly to `kwargs`?

2022-04-21 03:42 UTC, tk1012 commented on python/arachne/runtime/rpc/__init__.py
> +from .servicer import FileServicer, RuntimeServicer
An unused import

2022-04-21 03:42 UTC, tk1012 commented on python/arachne/runtime/rpc/__init__.py
> +from .servicer import FileServicer, RuntimeServicer
Unused imports

2022-04-21 03:42 UTC, tk1012 commented on python/arachne/runtime/rpc/__init__.py
>  from .server import create_channel, create_server, start_server
Could you remove `create_server` and `start_server`?
Because they are not used anymore.

2022-04-21 03:42 UTC, tk1012 commented on python/arachne/runtime/rpc/__init__.py
>  from .server import create_channel, create_server, start_server
Could you remove `create_server` and `start_server`?
Because they are not used anymore.

2022-04-21 03:42 UTC, tk1012 commented on python/arachne/runtime/rpc/servicer/servicer.py
> +            context.set_details("model_path should not be None")
Please change the message to "At least one of package_path or model_path must not be None".

2022-04-21 03:42 UTC, tk1012 commented on python/arachne/runtime/rpc/servicer/servicer.py
> +            context.set_details("model_path should not be None")
Please change the message to "At least one of package_path or model_path must not be None".

2022-04-21 03:42 UTC, tk1012 commented on python/arachne/runtime/rpc/servicer/servicer.py
> +            context.set_details(f"model_path {path} does not exist")
Please change the message to `f"path {path} does not exist"`.

2022-04-21 03:42 UTC, tk1012 commented on python/arachne/runtime/rpc/servicer/servicer.py
> +            context.set_details(f"model_path {path} does not exist")
Please change the message to `f"path {path} does not exist"`.

2022-04-22 03:00 UTC, lp6m commented
@ry3s Please modify document `docs/tutorials/run_runtime.rst` to match the code changes.

2022-04-22 05:29 UTC, ry3s commented
> @ry3s Please modify document `docs/tutorials/run_runtime.rst` to match the code changes.

Updated `docs/tutorials/run_runtime.rst` and `examples/run_runtime.ipynb`

2022-04-22 05:49 UTC, tk1012 requested changes

2022-04-22 05:49 UTC, tk1012 commented on python/arachne/runtime/rpc/__init__.py
> +    return RuntimeClient(channel, runtime, **args, **kwargs)
@ry3s Is `args` required?

I guess these assignments can replaced with `kwargs["package_path"] = package_tar`  and  `kwargs["model_path"] = model_file`

2022-04-22 05:49 UTC, tk1012 commented on python/arachne/runtime/rpc/servicer/servicer.py
> +            context.set_details("model_path should not be None")
@ry3s the message is still old.

2022-04-22 05:49 UTC, tk1012 commented on python/arachne/runtime/rpc/servicer/servicer.py
> +            context.set_details(f"model_path {path} does not exist")
@ry3s the message is still old.

2022-04-22 06:39 UTC, tk1012 requested changes

2022-04-22 06:39 UTC, tk1012 commented on docs/tutorials/run_runtime.rst
> +        runtime="tvm",
maybe `runtime="onnx",`

2022-04-22 06:39 UTC, tk1012 commented on python/arachne/runtime/rpc/__init__.py
> +    return RuntimeClient(channel, runtime, **args, **kwargs)
Is `args` required?

I guess these assignments can replaced with `kwargs["package_path"] = package_tar` and so on.
Then, return `RuntimeClient(channel, runtime, **kwargs)`.

2022-04-22 08:30 UTC, tk1012 approved these changes

2022-04-22 08:31 UTC, merged